version: "3"
services:
    flask_app:
        env_file: .env
        container_name: ${container_name_flask}
        build: ./flask_app
        image: ${image_name_flask}
        volumes:
            - ./flask_app/config/:${container_mountpoint_uwsgi}
            - ./flask_app/www/:${container_mountpoint_www}
        ports:
            - "${port_of_flask}"
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true 
        command: uwsgi --ini ${container_mountpoint_uwsgi}uwsgi.ini

    nginx:
        env_file: .env
        container_name: ${container_name_nginx}
        build: ./nginx
        image: ${image_name_nginx}
        volumes:
            - ./nginx/publich:/hostos/publich/
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/config/flask_app.conf:/etc/nginx/conf.d/flask_app.conf
        ports:
            - "${port_of_nginx}"
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true
        
    db57:
        env_file: .env
        build: ./db
        image: ${image_name_mysql}
        container_name: ${container_name_mysql}
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${USER_NAME}
            MYSQL_PASSWORD: ${USER_PASS}
            MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
            TZ: "Asia/Tokyo"
        ports:
            - "${port_of_mysql}"
